version: '3'
services:
  postgres:
    image: postgis/postgis:12-master
    restart: always
    environment:
      - POSTGRES_DB=regen_backend_challenge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./.postgres:/var/lib/postgresql/data
